projects:
  blog:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/app/API.service.service.ts
        docsFilePath: src/graphql
        maxDepth: 5
extensions:
  amplify:
    version: 3
